### PR TITLE
Fixed Readme for adding custom conf

### PR DESCRIPTION
**Pull request by LasaleFamine**
The custom configuration should be within the `config` object. Also the `colors` object is an array instead.

Ex: 

```js
module.exports = {
  config: {
    
    // Other options 
    ...


    colors: [
       ...
    ],

    theme: 'Palenight', 
    accentColor: '#64FFDA',
  }

...
```

### CODE REVIEW

**Comment by Rawnly** [comment]
`colors` is an object not an array

**Comment by LasaleFamine** [comment]
Am I the only one with an array for colors? That's part of my .hyper.js configuration file.

**Comment by Rawnly** [comment]
I think you have an old version of the `.hyper.js`, it doesn't update with hyper, try to backup the file and delete it. Hyper should create a new *conf file* then you can restore `css` etc

**Comment by LasaleFamine** [comment]
That's correct, also if I upgraded Hyper, I think just two weeks ago, now I needed to delete the config file and re-upgrade Hyper. Strange behaviour. 

So forget this, and thanks for the info!

**Comment by equinusocio** [comment]
@LasaleFamine 👎 😂

**Pull request closed without merging**
